<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


<ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
		
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.30" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.30">
	</PackageReference>
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
	<PackageReference Include="Npgsql" Version="8.0.9" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
</ItemGroup>


<ItemGroup>
  <ProjectReference Include="..\UserDetails-Module\UserDetails.Domain\UserDetails.Domain.csproj" />
</ItemGroup>
</Project>